### ISSUE TITLE
BDD / Produits

### ISSUE THREAD

**Issue by JeremyTablet** [TheCreationLab/Projet-M1-BigData#46]
Ajouter de nouvelles colonnes : 

* CR! = choix d'options restreint 

- grape_variety (cépage, texte)
- price_member (prix membre, chiffre)
- origin_continent (continent d'origine, texte, CR!)
- origin_country (pays d'origine, texte , CR!)
- origin_region (région d'origine, texte)
- description_short (description courte, texte)

++++

- product_range (gamme, texte CR!)

**Comment by weimdall** [comment]
origin_region et price_member pas encore ajouté

Colonne | Description
------------ | -------------
origin_region | Encore une nouvelle entités pour ça ?
price_member | C'est quoi ça ??

**Comment by JeremyTablet** [comment]
origin region ok 
price_menber : future version
