### ISSUE TITLE
Page Presse / Tableau des articles

### ISSUE THREAD

**Issue by nguyenanhduy1** [TheCreationLab/Projet-M1-BigData#51]
Bug sur les lignes de séparation entre les articles. Les lignes disparaissent selon les tailles d'écran.

**Comment by onlythepg** [comment]
Je pense que ça vient de la BDD d'Anh, aucun problème à constater sur Chrome et Firefox, même en l'ayant fait venir. Je passe l'issue en "A vérifier" pour être certain
